name: "CI"
on:
  push:
    branches:
      - "main"
env:
  RUST_VERSION: "1.92.0"
  GO_VERSION: "1.25.7"
  TINYGO_VERSION: "v0.39.0"
  NODE_VERSION: "24"
  PYTHON_VERSION: "3.13.0"
  SPIN_VERSION: ""
  AKAMAI_FUNCTIONS_DEPLOYMENT_NAME: "foobar"
jobs:
  spin:
    runs-on: "ubuntu-latest"
    name: Build Spin App
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Install TinyGo
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: "${{ env.TINYGO_VERSION }}"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "${{ env.RUST_VERSION }}"
          targets: wasm32-wasip1
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          plugins: 
      - name: Executing Setup Commands for complex
        run: python3 -m venv venv && source venv/bin/activate
        working-directory: .
      - name: Component Dependency Installation
        run: pip install -r requirements.txt
        working-directory: ./py-api
      - name: Build complex
        run: spin build
        working-directory: .
      - name: Install the aka Plugin for Spin
        run: spin plugins update && spin plugins install aka --yes
      - name: Login to Akamai Functions
        run: spin aka login --token ${{ secrets.AKAMAI_FUNCTIONS_TOKEN }}
      - name: Check if recurring App Deployment
        id: check-for-existing-app
        if: inputs.is_recurring_deployment
        run: |
          count=$(spin aka app list --account-id ${{ secrets.AKAMAI_FUNCTIONS_ACCOUNT_ID }} | grep ${{ env.AKAMAI_FUNCTIONS_DEPLOYMENT_NAME }} | wc -l)
          if [ "$count" -eq 0 ]; then
            echo "ERROR_MESSAGE=App with desired name not found in Akamai Functions account" >> $GITHUB_ENV
            exit 1
          fi
      - name: Link to existing App Deployment
        if: inputs.is_recurring_deployment
        run: spin aka app link --app-name ${{ env.AKAMAI_FUNCTIONS_DEPLOYMENT_NAME }} --account-id ${{ secrets.AKAMAI_FUNCTIONS_ACCOUNT_ID }}
      - name: Recurring Deployment to Akamai Functions
        if: inputs.is_recurring_deployment
        run: spin aka deploy --account-id ${{ secrets.AKAMAI_FUNCTIONS_ACCOUNT_ID }} --no-confirm
      - name: Deploy to Akamai Functions
        if: inputs.is_recurring_deployment == false
        run: spin aka deploy --account-id ${{ secrets.AKAMAI_FUNCTIONS_ACCOUNT_ID }} --create-name ${{ env.AKAMAI_FUNCTIONS_DEPLOYMENT_NAME }} --no-confirm